data:
    src: '~/torch_study/paper/file/klue-ner-v1_train.tsv'
    src_valid: '~/torch_study/paper/file/klue-ner-v1_dev.tsv'
    vocab:  '~/torch_study/paper/file/bert/vocab.json'
    max_len: 128
    nsp_prob: 0.5
    mask_ratio: 0.1
    batch_size: 128
model:
    pretrained_path: '~/torch_study/paper/06_BERT/mlruns/0/4035dd4c47fe43c6a507c0d74365211b/artifacts'
    hid_dim: 256
    n_layers: 2
    n_heads: 8
    pf_dim: 512
    dropout: 0.5

train:
    n_epochs: 20
    device: 'cuda'
    lr: 0.0005
    scheduler: True
    warmup_steps: 100
    train_nsp: False
    train_mlm: False