data:
    src: '/home/long8v/torch_study/paper/file/bert/bert.txt'
    src_valid: '/home/long8v/torch_study/paper/file/bert/bert_valid.txt'
    vocab:  '/home/long8v/torch_study/paper/file/bert/vocab.json'
    max_len: 128
    nsp_prob: 0.5
    mask_ratio: 0.1
    batch_size: 64
model:
    hid_dim: 256
    n_layers: 2
    n_heads: 8
    pf_dim: 512
    dropout: 0.5

train:
    n_epochs: 1000
    device: 'cuda'
    lr: 0.0005
    scheduler: True
    warmup_steps: 100