DATA:
  CHR_PAD_IDX: 0
  CHR_VOCAB_SIZE: 1299
  MAX_CHR_LEN: 4
  PREDICT_DIM: 12941
  TRG_PAD_IDX: 0
MODEL:
  CNN:
    DROPOUT: 0.5
    EMBEDDING_DIM: 1024
    FILTER_SIZES:
    - 2
    - 3
    - 4
    N_FILTERS: 10
    OUTPUT_DIM: 512
  HIGHWAY:
    HIGHWAY_N_LAYERS: 2
  LSTM:
    BIDIRECTIONAL: true
    DROPOUT: 0.5
    HID_DIM: 1024
    N_LAYERS: 2
TRAIN:
  DEVICE: cuda
  LR: 0.005
  N_EPOCHS: 100
