DATA:
    MINIMUM_SPACE_COUNT: 2
    TOKEN_MAX_LEN: 40
    CHR_MAX_LEN: 4
    BATCH_SIZE: 128
    TOKEN_MIN_FREQ: 10
    CHR_MIN_FREQ: 1
    
MODEL:
    CNN:
        EMBEDDING_DIM: 1024
        N_FILTERS: 10
        FILTER_SIZES: [2, 3, 4]
        OUTPUT_DIM: 512
        DROPOUT: 0.5

    HIGHWAY:
        HIGHWAY_N_LAYERS: 2

    LSTM:
        HID_DIM: 1024
        N_LAYERS: 2
        DROPOUT: 0.5
        BIDIRECTIONAL: True

TRAIN:
    LR: 0.005
    N_EPOCHS: 100
    DEVICE: cuda
    SCEHDULER: True