DATA:
    minimum_space_count: 2
    token_max_len: 40
    chr_max_len: 3
    batch_size: 64
MODEL:
    CNN:
        EMBEDDING_DIM: 1024
        N_FILTERS: 10
        FILTER_SIZES: [1, 2, 3]
        OUTPUT_DIM: 512
        DROPOUT: 0.5

    Highway:
        HIGHWAY_N_LAYERS: 1

    LSTM:
        HID_DIM: 1024
        N_LAYERS: 2
        DROPOUT: 0.5
        BIDIRECTIONAL: True

TRAIN:
    LR: 0.000005
    N_EPOCHS: 100
    DEVICE: cuda